final categories = [
  {
    "id": "0",
    "title": "Vegetables",
    "imageUrl": "assets/images/category/vegetables.png",
  },
  {
    "id": "1",
    "title": "Fruits",
    "imageUrl": "assets/images/category/fruits.png",
  },
  {
    "id": "2",
    "title": "Milk & Eggs",
    "imageUrl": "assets/images/category/milk.png",
  },
  {
    "id": "3",
    "title": "Drinks",
    "imageUrl": "assets/images/category/drinks.png",
  },
  {
    "id": "0",
    "title": "Vegetables",
    "imageUrl": "assets/images/category/vegetables.png",
  },
  {
    "id": "1",
    "title": "Fruits",
    "imageUrl": "assets/images/category/fruits.png",
  },
  {
    "id": "2",
    "title": "Milk & Eggs",
    "imageUrl": "assets/images/category/milk.png",
  },
  {
    "id": "3",
    "title": "Drinks",
    "imageUrl": "assets/images/category/drinks.png",
  },
];

final products = [
  {
    "id": "0",
    "title": "Fresh Oranage",
    "imageUrl": "assets/images/category/vegetables.png",
    "size": 1,
    "price": 12.00,
    "old_price": 14.00,
    "category": "Fruit",
  },
  {
    "id": "1",
    "title": "Fresh Fruits",
    "imageUrl": "assets/images/category/fruits.png",
    "size": 5,
    "price": 12.00,
    "old_price": 14.00,
    "category": "Fruit",
  },
  {
    "id": "2",
    "title": "Fresh Milk & Eggs",
    "imageUrl": "assets/images/category/milk.png",
    "size": 2,
    "price": 12.00,
    "old_price": 14.00,
    "category": "Milk & Eggs",
  },
  {
    "id": "3",
    "title": "Fresh Drinks",
    "imageUrl": "assets/images/category/drinks.png",
    "size": 1,
    "price": 12.00,
    "old_price": 14.00,
    "category": "Drink",
  },
  {
    "id": "1",
    "title": "Fresh Fruits",
    "imageUrl": "assets/images/category/fruits.png",
    "size": 5,
    "price": 12.00,
    "old_price": 14.00,
    "category": "Fruit",
  },
  {
    "id": "2",
    "title": "Fresh Milk & Eggs",
    "imageUrl": "assets/images/category/milk.png",
    "size": 2,
    "price": 12.00,
    "old_price": 14.00,
    "category": "Milk & Eggs",
  },
  {
    "id": "3",
    "title": "Fresh Drinks",
    "imageUrl": "assets/images/category/drinks.png",
    "size": 1,
    "price": 12.00,
    "old_price": 14.00,
    "category": "Drink",
  },
  {
    "id": "1",
    "title": "Fresh Fruits",
    "imageUrl": "assets/images/category/fruits.png",
    "size": 5,
    "price": 12.00,
    "old_price": 14.00,
    "category": "Fruit",
  },
  {
    "id": "2",
    "title": "Fresh Milk & Eggs",
    "imageUrl": "assets/images/category/milk.png",
    "size": 2,
    "price": 12.00,
    "old_price": 14.00,
    "category": "Vegetable",
  },
  {
    "id": "3",
    "title": "Fresh Drinks",
    "imageUrl": "assets/images/category/drinks.png",
    "size": 1,
    "price": 12.00,
    "old_price": 14.00,
    "category": "Drink",
  },
];
